/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as SupportRouteImport } from './routes/support'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminFeaturesRouteImport } from './routes/admin.features'
import { Route as AdminFinancesRouteImport } from './routes/admin.finances'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as TemplatesIndexRouteImport } from './routes/templates.index'
import { Route as TemplatesSlugRouteImport } from './routes/templates.$slug'
import { Route as ApiPublicPaymentsSwychrWebhookRouteImport } from './routes/api.public.payments.swychr.webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeaturesRoute = AdminFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinancesRoute = AdminFinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesSlugRoute = TemplatesSlugRouteImport.update({
  id: '/templates/$slug',
  path: '/templates/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsSwychrWebhookRoute =
  ApiPublicPaymentsSwychrWebhookRouteImport.update({
    id: '/api/public/payments/swychr/webhook',
    path: '/api/public/payments/swychr/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/settings': typeof SettingsRouteWithChildren
  '/subscribe': typeof SubscribeRoute
  '/support': typeof SupportRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/finances': typeof AdminFinancesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/users': typeof AdminUsersRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/templates/$slug': typeof TemplatesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/api/public/payments/swychr/webhook': typeof ApiPublicPaymentsSwychrWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/settings': typeof SettingsRouteWithChildren
  '/subscribe': typeof SubscribeRoute
  '/support': typeof SupportRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/finances': typeof AdminFinancesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/users': typeof AdminUsersRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/templates/$slug': typeof TemplatesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/api/public/payments/swychr/webhook': typeof ApiPublicPaymentsSwychrWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/settings': typeof SettingsRouteWithChildren
  '/subscribe': typeof SubscribeRoute
  '/support': typeof SupportRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/finances': typeof AdminFinancesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/users': typeof AdminUsersRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/templates/$slug': typeof TemplatesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/api/public/payments/swychr/webhook': typeof ApiPublicPaymentsSwychrWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/settings'
    | '/subscribe'
    | '/support'
    | '/admin/features'
    | '/admin/finances'
    | '/admin/logs'
    | '/admin/support'
    | '/admin/team'
    | '/admin/users'
    | '/settings/profile'
    | '/templates/$slug'
    | '/admin/'
    | '/templates/'
    | '/api/public/payments/swychr/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/settings'
    | '/subscribe'
    | '/support'
    | '/admin/features'
    | '/admin/finances'
    | '/admin/logs'
    | '/admin/support'
    | '/admin/team'
    | '/admin/users'
    | '/settings/profile'
    | '/templates/$slug'
    | '/admin'
    | '/templates'
    | '/api/public/payments/swychr/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/settings'
    | '/subscribe'
    | '/support'
    | '/admin/features'
    | '/admin/finances'
    | '/admin/logs'
    | '/admin/support'
    | '/admin/team'
    | '/admin/users'
    | '/settings/profile'
    | '/templates/$slug'
    | '/admin/'
    | '/templates/'
    | '/api/public/payments/swychr/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SubscribeRoute: typeof SubscribeRoute
  SupportRoute: typeof SupportRoute
  TemplatesSlugRoute: typeof TemplatesSlugRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  ApiPublicPaymentsSwychrWebhookRoute: typeof ApiPublicPaymentsSwychrWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/features': {
      id: '/admin/features'
      path: '/features'
      fullPath: '/admin/features'
      preLoaderRoute: typeof AdminFeaturesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finances': {
      id: '/admin/finances'
      path: '/finances'
      fullPath: '/admin/finances'
      preLoaderRoute: typeof AdminFinancesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$slug': {
      id: '/templates/$slug'
      path: '/templates/$slug'
      fullPath: '/templates/$slug'
      preLoaderRoute: typeof TemplatesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/swychr/webhook': {
      id: '/api/public/payments/swychr/webhook'
      path: '/api/public/payments/swychr/webhook'
      fullPath: '/api/public/payments/swychr/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsSwychrWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminFeaturesRoute: typeof AdminFeaturesRoute
  AdminFinancesRoute: typeof AdminFinancesRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFeaturesRoute: AdminFeaturesRoute,
  AdminFinancesRoute: AdminFinancesRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SettingsRouteChildren {
  SettingsProfileRoute: typeof SettingsProfileRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsProfileRoute: SettingsProfileRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SubscribeRoute: SubscribeRoute,
  SupportRoute: SupportRoute,
  TemplatesSlugRoute: TemplatesSlugRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  ApiPublicPaymentsSwychrWebhookRoute: ApiPublicPaymentsSwychrWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
